export const initialState = {
  artists: {
    1: {
      id: 1,
      name: "Quim da Sirene dos Bombeiros",
      age: 36,
      city: "Porto",
      nationality: "Portuguese",
      email: "quimquimquimdasirene.com",
      photo: "",
    },
    2: {
      id: 2,
      name: "The Kid Laroi",
      age: 18,
      city: "Sydney",
      nationality: "Australian",
      email: "support@bookingagentinfo.com",
      photo: "",
    },
    3: {
      id: 3,
      name: "Antonio da Silva",
      age: 20,
      city: "Porto",
      nationality: "Portuguese",
      email: "support@bookingagentinfo.com",
      photo: "",
    },
    4: {
      id: 4,
      name: "Manel",
      age: 40,
      city: "Coimbra",
      nationality: "Portuguese",
      email: "xxx@xxx.xxx",
      photo: "",
    },
    5: {
      id: 5,
      name: "Parra dos Porres",
      age: 68,
      city: "Braga",
      nationality: "portuguese",
      email: "parra@hotmail.com",
      photo: "",
    },
    6: {
      id: 6,
      name: "Zé Cabra",
      age: 50,
      city: "Cabral",
      nationality: "Portuguese",
      email: "9277@gmail.com89203",
      photo: "",
    },
    7: {
      id: 7,
      name: "Melanie Martinez",
      age: 26,
      city: "New York",
      nationality: "American",
      email: "dmcaagent@wmg.com7789",
      photo: "",
    },
    8: {
      id: 8,
      name: "Aurora",
      age: 25,
      city: "Stavanger",
      nationality: "Norwegian",
      email: "aurora@gmail.com",
      photo: "",
    },
    9: {
      id: 9,
      name: "LoveLeo",
      age: 23,
      city: "New York City",
      nationality: "American",
      email: "loveleo@gmail.com",
      photo: "",
    },
    10: {
      id: 10,
      name: "Doja Cat",
      age: 26,
      city: "Los Angeles",
      nationality: "American",
      email: "doja@gmail.com",
      photo: "",
    },
    11: {
      id: 11,
      name: "BBNO$",
      age: 26,
      city: "Vancouver",
      nationality: "Canadian",
      email: "bbno@gmail.com",
      photo: "",
    },
    12: {
      id: 12,
      name: "Des Rocs",
      age: 23,
      city: "New York",
      nationality: "American",
      email: "desrocs@gmail.com",
      photo: "",
    },
    13: {
      id: 13,
      name: "Børns",
      age: 30,
      city: "Muskegon",
      nationality: "American",
      email: "borns@gmail.com",
      photo: "",
    },
    14: {
      id: 14,
      name: "SEB",
      age: 24,
      city: "Los Angeles",
      nationality: "American",
      email: "seb@gmail.com",
      photo: "",
    },

    songs: {
      1: {
        name: "Thousand Miles",
        artistId: 2,
        genre: "rap",
        year: 2022,
        album: "KIDS ARE GROWING UP",
        albumArt: "https://i.imgur.com/XqQXKZY.jpg",
      },
      2:{
        name: " I'm a Believer",
        artistId: 2,
        genre: "rap",
        year: 2020,
        album: "KIDS ARE KIDDING",
        albumArt: "https://i.imgur.com/XqQXKZY.jpg",
      },
      3: {
        name: "Enough",
        artistId: 4,
        genre: "pop",
        year: 2010,
        album: "Enough",
        albumArt: "https://i.imgur.com/XqQXKZY.jpg",
      },
      4:{
        name: "One",
        artistId: 5,
        genre: "fado",
        year: 2050,
        album: "One",
        albumArt: "https://i.imgur.com/XqQXKZY.jpg",
      },
      5:{
        name: "Foo",
        artistId: 6,
        genre: "rock",
        year: 1990,
        album: "Goo",
        albumArt: "https://i.imgur.com/XqQXKZY.jpg",
      },
      6:{
        name: "Bar",
        artistId: 7,
        genre: "samba",
        year: 2021,
        album: "DortBar",
        albumArt: "https://i.imgur.com/XqQXKZY.jpg",
      },
      7:{
        name: "Baz",
        artistId: 8,
        genre: "rock",
        year: 2017,
        album: "Zoo",
        albumArt: "https://i.imgur.com/XqQXKZY.jpg",
      }, 
      8:{
        name: "Qux",
        artistId: 9,
        genre: "rock",
        year: 2020,
        album: "Qux Release",
        albumArt: "https://i.imgur.com/XqQXKZY.jpg",
      },
      9:{
        name: "Terquede",
        artistId: 10,
        genre: "rock",
        year: 2005,
        album: "Terquede",
        albumArt: "https://i.imgur.com/XqQXKZY.jpg",
      },
      10:{
        name: "Quinze",
        artistId: 11,
        genre: "rock",
        year: 2020,
        album: "Quinze Release",
        albumArt: "https://i.imgur.com/XqQXKZY.jpg",
      },
      11:{
        name: "Guitar",
        artistId: 12,
        genre: "rock",
        year: 2020,
        album: "Guitar Release",
        albumArt: "https://i.imgur.com/XqQXKZY.jpg",
      },
      12:{
        name: "Bass",
        artistId: 13,
        genre: "rock",
        year: 2020,
        album: "Bass Release",
        albumArt: "https://i.imgur.com/XqQXKZY.jpg",
      },
      13:{
        name: "Drums",
        artistId: 14,
        genre: "samba",
        year: 2020,
        album: "Drums Release",
        albumArt: "https://i.imgur.com/XqQXKZY.jpg",
      },
      14:{
        name: "Piano",
        artistId: 15,
        genre: "rock",
        year: 2020,
        album: "Piano Release",
        albumArt: "https://i.imgur.com/XqQXKZY.jpg",
      }
    },
  },
  genre: ["rock", "pop", "samba", "fado", "corridinho", "rap"],
};
